; The Dawn of the Tiberium Age (DTA) CnCNet Client settings
; Created by Rampastring
; http://www.moddb.com/members/rampastring
; If you use or redistribute the client in any public projects, please include
; Rampastring and The Dawn of the Tiberium Age in your project's credits.

[General]
; List of sides / countries. Has to match the order of countries / houses in rules.ini.
Sides=Atreides,Harkonnen,Ordos
; List of side indices used when writing player spawn info instead of Sides list indices.
;InternalSideIndices=0,1,2
; Single side index to use when writing spectator spawn info instead of a random Sides list index.
;SpectatorInternalSideIndex=0
StartingLocationAngularVelocity=0.01
ReservedStartingLocationAngularVelocity=0.01


; Multiplayer colors. Syntax: <Name>=R,G,B,<in-game color index>
[MPColors]
Yellow=230,220,13,0
Red=255,25,25,1
Blue=34,107,212,2
Green=61,210,45,3
Orange=255,160,25,4
Light Blue=49,217,230,5
Purple=146,40,189,6
Pink=255,153,237,7

; Defines settings that are used in the CnCNet Game Lobby UI.
[MultiplayerGameLobby]
CheckBoxes=chkCrates,chkShortGame,chkWorms,chkDisableEngineer,chkDisableCarryall,chkDisableTurrets
DropDowns=cmbCredits,cmbStartingUnits,cmbGameSpeedCap,cmbTechLevel
Labels=lblGameSpeedCap,lblCredits,lblStartingUnits,lblTechLevel
PlayerReadyBoxY=2
PlayerReadyBoxX=6
PlayerOptionLocationX=29
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=9
PlayerOptionHorizontalMargin=5
PlayerOptionCaptionLocationY=6
PlayerNameWidth=120
SideWidth=155
ColorWidth=85
StartWidth=45
TeamWidth=35

; Defines settings that are used in the Skirmish Game Lobby UI.
[SkirmishLobby]
CheckBoxes=chkCrates,chkShortGame,chkWorms,chkDisableEngineer,chkDisableCarryall,chkDisableTurrets
DropDowns=cmbCredits,cmbStartingUnits,cmbSkirmishGameSpeedCap,cmbTechLevel
Labels=lblGameSpeedCap,lblCredits,lblStartingUnits,lblTechLevel
PlayerOptionLocationX=12
PlayerOptionLocationY=25
PlayerOptionVerticalMargin=9
PlayerOptionHorizontalMargin=5
PlayerOptionCaptionLocationY=6
PlayerNameWidth=120
SideWidth=155
ColorWidth=85
StartWidth=50
TeamWidth=45

; Keys that are ALWAYS written to spawn.ini when the game starts.
; These can be overriden by gamemode-specific code.
[ForcedSpawnIniOptions]
FogOfWar=No

; Locations of objects will appear 2 pixels to the right and 6 pixels down from the specified coordinate.
; Reversed=yes will make an enabled checkbox set the associated key to =False instead of =True.

;=====================
;; Dropdowns
;=====================

[lblCredits]
Text=Credits:
Location=903,230

[cmbCredits]
OptionName=Starting Credits
Items=50000,30000,20000,10000,7000,5000,3000
DefaultIndex=4
SpawnIniOption=Credits
DataWriteMode=String
Location=903,250
Size=120,22

[lblGameSpeedCap]
Text=Game Speed:
Location=903,180

[cmbGameSpeedCap]
OptionName=Game Speed
Items=Fastest (60 FPS),Faster (45 FPS),Fast (30 FPS),Medium (20 FPS),Slow (15 FPS),Slower (12 FPS),Slowest (10 FPS)
DefaultIndex=2
SpawnIniOption=GameSpeed
DataWriteMode=Index
Location=903,200
Size=120,22

[cmbSkirmishGameSpeedCap]
OptionName=Game Speed
Items=Fastest (MAX),Faster (60 FPS),Fast (30 FPS),Medium (20 FPS),Slow (15 FPS),Slower (12 FPS),Slowest (10 FPS)
DefaultIndex=2
SpawnIniOption=GameSpeed
DataWriteMode=Index
Location=903,200
Size=120,22

[lblStartingUnits]
Text=Starting Units:
Location=1060,180

[cmbStartingUnits]
OptionName=Starting Units
Items=10,9,8,7,6,5,4,3,2,1,0
DefaultIndex=10
SpawnIniOption=UnitCount
DataWriteMode=String
Location=1060,200
Size=120,22

[lblTechLevel]
Text=Tech Level:
Location=1060,230

[cmbTechLevel]
OptionName=Tech Level
Items=7,6,5,4,3,2,1
DefaultIndex=0
SpawnIniOption=TechLevel
DataWriteMode=String
Location=1060,250
Size=120,22
Enabled=yes
Visible=yes

;============================
;; Left Column of Checkboxes
;============================

[chkShortGame]
Text=Short Game
SpawnIniOption=ShortGame
Checked=True
Location=903,24
ToolTip=Players win when all enemy buildings are destroyed.

[chkCrates]
Text=Crates Appear
SpawnIniOption=Crates
Checked=False
Location=903,45
ToolTip=Random power-up crates will appear.

[chkWorms]
Text=Worms
SpawnIniOption=Worms
Checked=False
Location=903,66
ToolTip=Enable sandworm spawning.

;============================
;; Right Column of Checkboxes
;============================

[chkDisableEngineer]
Text=Disable Engineer
SpawnIniOption=DisableEngineer
Checked=False
Location=1060,24
ToolTip=Disable engineer unit production.

[chkDisableCarryall]
Text=Disable Carryall
SpawnIniOption=DisableCarryall
Checked=False
Location=1060,45
ToolTip=Disable carryall unit production.

[chkDisableTurrets]
Text=Disable Turrets
SpawnIniOption=DisableTurrets
Checked=False
Location=1060,66
ToolTip=Disable turret construction.
