;Rename this file to "Servers.ini" to activate it
[Servers]
IRCServer1=Prothid.NY.US.GameSurge.Net:6667
IRCServer2=192.223.27.109:5960
IRCServer3=Gameservers.NJ.US.GameSurge.net:8080
IRCServer4=NuclearFallout.WA.US.GameSurge.net:5960
IRCServer5=Burstfire.UK.EU.GameSurge.net:7000
IRCServer6=ColoCrossing.IL.US.GameSurge.net:6660
IRCServer7=Krypt.CA.US.GameSurge.net:6669
IRCServer8=Portlane.SE.EU.GameSurge.net:6668
IRCServer9=TAL.DE.EU.GameSurge.net:6666
TunnelMasterList=http://cncnet.org/master-list
MapDBdownload=http://mapdb.cncnet.org/
MapDBupload=http://mapdb.cncnet.org/upload
TunnelServerStatus=http://cncnet.org/status
LiveStreamChannels=http://funkyfr3sh.cnc-comm.com/livestream/channels
CrashDBupload=http://api.cncnet.org/crash
WhatIsMyIpApi=http://funkyfr3sh.cnc-comm.com/ip/
ServerWebsite=www.cncnet.org
TiberianDawnPatch=http://nyerguds.arsaneus-design.com/cnc95upd/cc95p106/
Dune2000Download=http://gruntmods.com/?page_id=19
NatTraversalGuide=http://forums.cncnet.org/index.php?topic=5635.0
YouTube=https://www.youtube.com/user/CnCNetOfficial
Facebook=http://facebook.com/cncnet
Discord=https://discord.gg/phmEDuX
Twitter=http://twitter.com/cncnetofficial
LiveStream=http://cncnet.org/live
TwitchApi=https://api.twitch.tv/kraken/streams/
